name: Tests

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & run tests
        run: |
          npm install
          npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # https://github.com/olegtarasov/get-tag
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false

      - name: Publish to npm
        run: |
          npm install
          npm run build
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
