name: Running All Tests and Publish to NPM

on:
  push:
    tags:
      - '*-prod'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # https://github.com/olegtarasov/get-tag
    - name: Get Tag Name
      uses: olegtarasov/get-tag@v2
      id: tagName

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tagName.outputs.tag }}
        release_name: ${{ steps.tagName.outputs.tag }}
        draft: false
        prerelease: false

    - name: Install dependencies & run tests
      run: |
        export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
        npm install
        npm run test

    - name: Publish to npm
      run: |
        npm run build
        npm publish
      env:
        NPM_TOKEN=${{ secrets.NPM_TOKEN }}
